In [1]:

import pandas as pd

job=pd.read_excel('CompiledAnalyticsData_excel.xlsx')
job.head(3)


Unnamed: 0  Unnamed: 0.1  ID     Job Class  \
0           0             0   0  Data Analyst   
1           1             1   1  Data Analyst   
2           2             2   2  Data Analyst   

                                           Job Title  \
0  Data Analyst, Center on Immigration and Justic...   
1                               Quality Data Analyst   
2  Senior Data Analyst, Insights & Analytics Team...   

              Salary Estimate  \
0  $37K-$66K (Glassdoor est.)   
1  $37K-$66K (Glassdoor est.)   
2  $37K-$66K (Glassdoor est.)   

                                     Job Description  Rating  \
0  Are you eager to roll up your sleeves and harn...     3.2   
1  Overview\n\nProvides analytical and technical ...     3.8   
2  We’re looking for a Senior Data Analyst who ha...     3.4   

                              Company Name      Location  ... Founded  \
0           Vera Institute of Justice\n3.2  New York, NY  ...    1961   
1  Visiting Nurse Service of New York\n3.8  New York, NY  ...    1893   
2                         Squarespace\n3.4  New York, NY  ...    2003   

        Type of ownership                          Industry  \
0  Nonprofit Organization                 Social Assistance   
1  Nonprofit Organization  Health Care Services & Hospitals   
2       Company - Private                          Internet   

                   Sector                     Revenue Competitors Easy Apply  \
0              Non-Profit  $100 to $500 million (USD)          -1          1   
1             Health Care      $2 to $5 billion (USD)          -1         -1   
2  Information Technology    Unknown / Non-Applicable     GoDaddy         -1   

                                     Clean Job Title  \
0        DATA ANALYST CENTER IMMIGRATION JUSTICE CIJ   
1                               QUALITY DATA ANALYST   
2  SENIOR DATA ANALYST INSIGHTS GAME TEAM CUSTOME...   

                               Clean Job Description  \
0  taking party call record set impede real eager...   
1  train trend PLSQL topic dashborads computersci...   
2  dset dublin iconic dashborads master acting li...   

                                              skills  
0          ['sql', 'aws', 'python', 'r', 'analysis']  
1  ['computerscience', 'master', 'analytics', 'he...  
2  ['master', 'sql', 'engineering', 'phd', 'table...  

[3 rows x 22 columns]

In [ ]:
#job['skill']=job['skills'].replace('[^A-Za-z0-9]+',' ',regex=True)

In [2]:
job['JobClass']=job['Job Class']
job['CleanJobDescription']=job['Clean Job Description']

In [3]:
cleanjb=job['CleanJobDescription'].values.astype('str')


In [4]:
jobgroup = job.groupby("JobClass")
len(jobgroup)
jobgroup.head()

Unnamed: 0  Unnamed: 0.1    ID         Job Class  \
0              0             0     0      Data Analyst   
1              1             1     1      Data Analyst   
2              2             2     2      Data Analyst   
3              3             3     3      Data Analyst   
4              4             4     4      Data Analyst   
2252        2252          2252  2252     Data Engineer   
2253        2253          2253  2253     Data Engineer   
2254        2254          2254  2254     Data Engineer   
2255        2255          2255  2255     Data Engineer   
2256        2256          2256  2256     Data Engineer   
4780        4780          4780  4780    Data Scientist   
4781        4781          4781  4781    Data Scientist   
4782        4782          4782  4782    Data Scientist   
4783        4783          4783  4783    Data Scientist   
4784        4784          4784  4784    Data Scientist   
8689        8689          8689  8689  Business Analyst   
8690        8690          8690  8690  Business Analyst   
8691        8691          8691  8691  Business Analyst   
8692        8692          8692  8692  Business Analyst   
8693        8693          8693  8693  Business Analyst   

                                              Job Title  \
0     Data Analyst, Center on Immigration and Justic...   
1                                  Quality Data Analyst   
2     Senior Data Analyst, Insights & Analytics Team...   
3                                          Data Analyst   
4                                Reporting Data Analyst   
2252                                      Data Engineer   
2253  Senior Data Engineer (Healthcare Domain experi...   
2254                                     Data Engineers   
2255                      Client Trade Support Engineer   
2256                                      Data Engineer   
4780                              Senior Data Scientist   
4781                  Data Scientist, Product Analytics   
4782                               Data Science Manager   
4783                                       Data Analyst   
4784                             Director, Data Science   
8689   Business Analyst - Clinical & Logistics Platform   
8690                                   Business Analyst   
8691                                       Data Analyst   
8692    Information Security Analyst, Incident Response   
8693                      Analyst - FP&A Global Revenue   

                   Salary Estimate  \
0       $37K-$66K (Glassdoor est.)   
1       $37K-$66K (Glassdoor est.)   
2       $37K-$66K (Glassdoor est.)   
3       $37K-$66K (Glassdoor est.)   
4       $37K-$66K (Glassdoor est.)   
2252   $80K-$150K (Glassdoor est.)   
2253   $80K-$150K (Glassdoor est.)   
2254   $80K-$150K (Glassdoor est.)   
2255   $80K-$150K (Glassdoor est.)   
2256   $80K-$150K (Glassdoor est.)   
4780  $111K-$181K (Glassdoor est.)   
4781  $111K-$181K (Glassdoor est.)   
4782  $111K-$181K (Glassdoor est.)   
4783  $111K-$181K (Glassdoor est.)   
4784  $111K-$181K (Glassdoor est.)   
8689   $56K-$102K (Glassdoor est.)   
8690   $56K-$102K (Glassdoor est.)   
8691   $56K-$102K (Glassdoor est.)   
8692   $56K-$102K (Glassdoor est.)   
8693   $56K-$102K (Glassdoor est.)   

                                        Job Description  Rating  \
0     Are you eager to roll up your sleeves and harn...     3.2   
1     Overview\n\nProvides analytical and technical ...     3.8   
2     We’re looking for a Senior Data Analyst who ha...     3.4   
3     Requisition NumberRR-0001939\nRemote:Yes\nWe c...     4.1   
4     ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...     3.9   
2252  Company Description\nSagence is a management a...     4.5   
2253  Key Responsibilities\n\n- Architect, build, an...     3.4   
2254  Overview\n\nJob description\n\nPosition Overvi...     5.0   
2255  About the Position\n\n\nThis position will sup...     4.8   
2256  Data Engineer\n\nJob Details\nLevel\nExperienc...     3.7   
4780  ABOUT

In [5]:
jobgroup.describe()

Unnamed: 0                                                  \
                      count     mean          std     min      25%      50%   
JobClass                                                                      
Business Analyst     3692.0  10534.5  1065.932925  8689.0  9611.75  10534.5   
Data Analyst         2252.0   1125.5   650.240725     0.0   562.75   1125.5   
Data Engineer        2528.0   3515.5   729.915064  2252.0  2883.75   3515.5   
Data Scientist       3909.0   6734.0  1128.575429  4780.0  5757.00   6734.0   

                                    Unnamed: 0.1           ... Founded  \
                       75%      max        count     mean  ...     75%   
JobClass                                                   ...           
Business Analyst  11457.25  12380.0       3692.0  10534.5  ...  2002.0   
Data Analyst       1688.25   2251.0       2252.0   1125.5  ...  2002.0   
Data Engineer      4147.25   4779.0       2528.0   3515.5  ...  2003.0   
Data Scientist     7711.00   8688.0       3909.0   6734.0  ...  2002.0   

                         Easy Apply                                          \
                     max      count      mean       std  min  25%  50%  75%   
JobClass                                                                      
Business Analyst  2020.0     3692.0 -0.927952  0.372749 -1.0 -1.0 -1.0 -1.0   
Data Analyst      2019.0     2252.0 -0.928952  0.370282 -1.0 -1.0 -1.0 -1.0   
Data Engineer     2020.0     2528.0 -0.884494  0.466644 -1.0 -1.0 -1.0 -1.0   
Data Scientist    2020.0     3909.0 -0.916091  0.401022 -1.0 -1.0 -1.0 -1.0   

                       
                  max  
JobClass               
Business Analyst  1.0  
Data Analyst      1.0  
Data Engineer     1.0  
Data Scientist    1.0  

[4 rows x 48 columns]

In [6]:
print(job.shape)

(12381, 24)


In [7]:

#split the data into training and testing

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cleanjb, job.JobClass, test_size=0.33, random_state=12)



In [8]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()


In [9]:
#Build training pipeline using  Naïve Bayes Model

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

text_clf = Pipeline([('vect', CountVectorizer()),   #Vectorizer
                     ('tfidf', TfidfTransformer()), #DTM with TFIDF
                      ('clf', MultinomialNB()),     #ML Model
                    ])


In [10]:
text_clf.fit(X_train,y_train) 

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB())])

In [11]:
#Evaluate the model

import numpy as np
from sklearn import metrics

predicted = text_clf.predict(X_test)

print(metrics.confusion_matrix(y_test, predicted))


[[1022   14    8  179]
 [ 309   67    9  341]
 [ 116    0  232  493]
 [ 170   27   87 1012]]


In [12]:
print("NB:",np.mean(predicted == y_test) )

NB: 0.5709740577581988


In [13]:
print(metrics.classification_report(y_test, predicted))

                  precision    recall  f1-score   support

Business Analyst       0.63      0.84      0.72      1223
    Data Analyst       0.62      0.09      0.16       726
   Data Engineer       0.69      0.28      0.39       841
  Data Scientist       0.50      0.78      0.61      1296

        accuracy                           0.57      4086
       macro avg       0.61      0.50      0.47      4086
    weighted avg       0.60      0.57      0.52      4086



In [14]:
#Build training pipeline using  Decision Tree Model


from sklearn import tree
text_clf = Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf', tree.DecisionTreeClassifier())])
clf = text_clf.fit(X_train, y_train) 

predicted = clf.predict(X_test)
  

In [15]:
print(metrics.confusion_matrix(y_test, predicted))


[[849 176  70 128]
 [191 330  35 170]
 [ 83  36 425 297]
 [173 216 315 592]]


In [16]:
print("DT:",np.mean(predicted == y_test) )

DT: 0.5374449339207048


In [17]:
print(metrics.classification_report(y_test, predicted))

                  precision    recall  f1-score   support

Business Analyst       0.66      0.69      0.67      1223
    Data Analyst       0.44      0.45      0.44       726
   Data Engineer       0.50      0.51      0.50       841
  Data Scientist       0.50      0.46      0.48      1296

        accuracy                           0.54      4086
       macro avg       0.52      0.53      0.52      4086
    weighted avg       0.54      0.54      0.54      4086



In [18]:
#Build training pipeline using  SVM Model


from sklearn import svm
from sklearn.svm import SVC

from sklearn.linear_model import SGDClassifier
text_clf = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer(use_idf=True)),
                      ('clf', svm.LinearSVC(C=1.0))
                    ])
text_clf.fit(X_train, y_train) 
    
predicted = text_clf.predict(X_test)
 


In [19]:
print(metrics.confusion_matrix(y_test, predicted))


[[971 115  37 100]
 [162 355  27 182]
 [ 57  18 488 278]
 [117 218 236 725]]


In [20]:
print(np.mean(predicted == y_test) )


0.6213901125795399


In [21]:
print(metrics.classification_report(y_test, predicted))

                  precision    recall  f1-score   support

Business Analyst       0.74      0.79      0.77      1223
    Data Analyst       0.50      0.49      0.50       726
   Data Engineer       0.62      0.58      0.60       841
  Data Scientist       0.56      0.56      0.56      1296

        accuracy                           0.62      4086
       macro avg       0.61      0.61      0.61      4086
    weighted avg       0.62      0.62      0.62      4086



In [22]:
test=pd.read_excel('V3.0 Project OA Data_excel_Testingdata.xlsx')
test.head(3)
test1=test['Clean Job Description']
test1=list(test1)
test1

['case deeplearning etl powerbi social net sas dw lake simple va q r admins bases mdm regression stack image video modelling python analytics  th medium',
 'image c cnn machine learning deeplearning decision tree pca lstm python  linux opencv like svm',
 'machine learning text mining scale would signal agile  line']

In [23]:
#Prediction on new documents
for i in test1:
    docs_new = [i]
    predicted = text_clf.predict(docs_new)
    print(predicted)

['Data Scientist']
['Data Scientist']
['Data Scientist']
