In [1]:
import numpy as np
import pandas as pd

job=pd.read_excel('CompiledAnalyticsData_excel.xlsx')
job.head(3)


Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  ID     Job Class  \
0           0             0               0   0  Data Analyst   
1           1             1               1   1  Data Analyst   
2           2             2               2   2  Data Analyst   

                                           Job Title  \
0  Data Analyst, Center on Immigration and Justic...   
1                               Quality Data Analyst   
2  Senior Data Analyst, Insights & Analytics Team...   

              Salary Estimate  \
0  $37K-$66K (Glassdoor est.)   
1  $37K-$66K (Glassdoor est.)   
2  $37K-$66K (Glassdoor est.)   

                                     Job Description  Rating  \
0  Are you eager to roll up your sleeves and harn...     3.2   
1  Overview\n\nProvides analytical and technical ...     3.8   
2  We’re looking for a Senior Data Analyst who ha...     3.4   

                              Company Name  ... Founded  \
0           Vera Institute of Justice\n3.2  ...    1961   
1  Visiting Nurse Service of New York\n3.8  ...    1893   
2                         Squarespace\n3.4  ...    2003   

        Type of ownership                          Industry  \
0  Nonprofit Organization                 Social Assistance   
1  Nonprofit Organization  Health Care Services & Hospitals   
2       Company - Private                          Internet   

                   Sector                     Revenue Competitors Easy Apply  \
0              Non-Profit  $100 to $500 million (USD)          -1          1   
1             Health Care      $2 to $5 billion (USD)          -1         -1   
2  Information Technology    Unknown / Non-Applicable     GoDaddy         -1   

                                     Clean Job Title  \
0        DATA ANALYST CENTER IMMIGRATION JUSTICE CIJ   
1                               QUALITY DATA ANALYST   
2  SENIOR DATA ANALYST INSIGHTS GAME TEAM CUSTOME...   

                               Clean Job Description  \
0  taking party call record set impede real eager...   
1  train trend PLSQL topic dashborads computersci...   
2  dset dublin iconic dashborads master acting li...   

                                              skills  
0          ['sql', 'aws', 'python', 'r', 'analysis']  
1  ['computerscience', 'master', 'analytics', 'he...  
2  ['master', 'sql', 'engineering', 'phd', 'table...  

[3 rows x 23 columns]

In [2]:
job['JobClass']=job['Job Class']
job['JobTitle']=job['Clean Job Title']

In [3]:
jobgroup = job.groupby("JobClass")
len(jobgroup)
jobgroup.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1    ID         Job Class  \
0              0             0               0     0      Data Analyst   
1              1             1               1     1      Data Analyst   
2              2             2               2     2      Data Analyst   
3              3             3               3     3      Data Analyst   
4              4             4               4     4      Data Analyst   
2252        2252          2252            2252  2252     Data Engineer   
2253        2253          2253            2253  2253     Data Engineer   
2254        2254          2254            2254  2254     Data Engineer   
2255        2255          2255            2255  2255     Data Engineer   
2256        2256          2256            2256  2256     Data Engineer   
4780        4780          4780            4780  4780    Data Scientist   
4781        4781          4781            4781  4781    Data Scientist   
4782        4782          4782            4782  4782    Data Scientist   
4783        4783          4783            4783  4783    Data Scientist   
4784        4784          4784            4784  4784    Data Scientist   
8689        8689          8689            8689  8689  Business Analyst   
8690        8690          8690            8690  8690  Business Analyst   
8691        8691          8691            8691  8691  Business Analyst   
8692        8692          8692            8692  8692  Business Analyst   
8693        8693          8693            8693  8693  Business Analyst   

                                              Job Title  \
0     Data Analyst, Center on Immigration and Justic...   
1                                  Quality Data Analyst   
2     Senior Data Analyst, Insights & Analytics Team...   
3                                          Data Analyst   
4                                Reporting Data Analyst   
2252                                      Data Engineer   
2253  Senior Data Engineer (Healthcare Domain experi...   
2254                                     Data Engineers   
2255                      Client Trade Support Engineer   
2256                                      Data Engineer   
4780                              Senior Data Scientist   
4781                  Data Scientist, Product Analytics   
4782                               Data Science Manager   
4783                                       Data Analyst   
4784                             Director, Data Science   
8689   Business Analyst - Clinical & Logistics Platform   
8690                                   Business Analyst   
8691                                       Data Analyst   
8692    Information Security Analyst, Incident Response   
8693                      Analyst - FP&A Global Revenue   

                   Salary Estimate  \
0       $37K-$66K (Glassdoor est.)   
1       $37K-$66K (Glassdoor est.)   
2       $37K-$66K (Glassdoor est.)   
3       $37K-$66K (Glassdoor est.)   
4       $37K-$66K (Glassdoor est.)   
2252   $80K-$150K (Glassdoor est.)   
2253   $80K-$150K (Glassdoor est.)   
2254   $80K-$150K (Glassdoor est.)   
2255   $80K-$150K (Glassdoor est.)   
2256   $80K-$150K (Glassdoor est.)   
4780  $111K-$181K (Glassdoor est.)   
4781  $111K-$181K (Glassdoor est.)   
4782  $111K-$181K (Glassdoor est.)   
4783  $111K-$181K (Glassdoor est.)   
4784  $111K-$181K (Glassdoor est.)   
8689   $56K-$102K (Glassdoor est.)   
8690   $56K-$102K (Glassdoor est.)   
8691   $56K-$102K (Glassdoor est.)   
8692   $56K-$102K (Glassdoor est.)   
8693   $56K-$102K (Glassdoor est.)   

                                        Job Description  Rating  \
0     Are you eager to roll up your sleeves and harn...     3.2   
1     Overview\n\nProvides analytical and technical ...     3.8   
2     We’re looking for a Senior Data Analyst who ha...     3.4   
3     Requisition NumberRR-0001939\nRemote:Yes\nWe c...     4.1   
4     ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...     3.9   
2252  Comp

In [4]:
jobgroup.describe()

Unnamed: 0                                                  \
                      count     mean          std     min      25%      50%   
JobClass                                                                      
Business Analyst     3692.0  10534.5  1065.932925  8689.0  9611.75  10534.5   
Data Analyst         2252.0   1125.5   650.240725     0.0   562.75   1125.5   
Data Engineer        2528.0   3515.5   729.915064  2252.0  2883.75   3515.5   
Data Scientist       3909.0   6734.0  1128.575429  4780.0  5757.00   6734.0   

                                    Unnamed: 0.1           ... Founded  \
                       75%      max        count     mean  ...     75%   
JobClass                                                   ...           
Business Analyst  11457.25  12380.0       3692.0  10534.5  ...  2002.0   
Data Analyst       1688.25   2251.0       2252.0   1125.5  ...  2002.0   
Data Engineer      4147.25   4779.0       2528.0   3515.5  ...  2003.0   
Data Scientist     7711.00   8688.0       3909.0   6734.0  ...  2002.0   

                         Easy Apply                                          \
                     max      count      mean       std  min  25%  50%  75%   
JobClass                                                                      
Business Analyst  2020.0     3692.0 -0.927952  0.372749 -1.0 -1.0 -1.0 -1.0   
Data Analyst      2019.0     2252.0 -0.928952  0.370282 -1.0 -1.0 -1.0 -1.0   
Data Engineer     2020.0     2528.0 -0.884494  0.466644 -1.0 -1.0 -1.0 -1.0   
Data Scientist    2020.0     3909.0 -0.916091  0.401022 -1.0 -1.0 -1.0 -1.0   

                       
                  max  
JobClass               
Business Analyst  1.0  
Data Analyst      1.0  
Data Engineer     1.0  
Data Scientist    1.0  

[4 rows x 56 columns]

In [5]:
print(job.shape)

(12381, 25)


In [6]:

#split the data into training and testing

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(job.JobTitle, job.JobClass, test_size=0.33, random_state=12)



In [7]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()


In [8]:
#Build training pipeline using  Naïve Bayes Model

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

text_clf1 = Pipeline([('vect', CountVectorizer()),   #Vectorizer
                     ('tfidf', TfidfTransformer()), #DTM with TFIDF
                      ('clf', MultinomialNB()),     #ML Model
                    ])

clf1=text_clf1.fit(X_train,y_train ) 


In [9]:
#Evaluate the model

import numpy as np
from sklearn import metrics

predicted1 = text_clf1.predict(X_test)

print(metrics.confusion_matrix(y_test, predicted1))


[[1058  102    9   54]
 [ 185  390   12  139]
 [  13    4  660  164]
 [ 107  165  210  814]]


In [10]:
print("NB:",np.mean(predicted1 == y_test) )

NB: 0.7151248164464024


In [11]:
print(metrics.classification_report(y_test, predicted1))

                  precision    recall  f1-score   support

Business Analyst       0.78      0.87      0.82      1223
    Data Analyst       0.59      0.54      0.56       726
   Data Engineer       0.74      0.78      0.76       841
  Data Scientist       0.70      0.63      0.66      1296

        accuracy                           0.72      4086
       macro avg       0.70      0.70      0.70      4086
    weighted avg       0.71      0.72      0.71      4086



In [12]:
#Build training pipeline using  Decision Tree Model


from sklearn import tree
text_clf2 = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer()),
                      ('clf', tree.DecisionTreeClassifier())
                    ])
clf2 = text_clf2.fit(X_train, y_train) 

predicted2 = clf2.predict(X_test)
  

In [13]:
print(metrics.confusion_matrix(y_test, predicted2))


[[1079  119    2   23]
 [  41  623    1   61]
 [   5    5  742   89]
 [  42  244  251  759]]


In [14]:
print("DT:",np.mean(predicted2 == y_test) )

DT: 0.7838962310327949


In [15]:
print(metrics.classification_report(y_test, predicted2))

                  precision    recall  f1-score   support

Business Analyst       0.92      0.88      0.90      1223
    Data Analyst       0.63      0.86      0.73       726
   Data Engineer       0.74      0.88      0.81       841
  Data Scientist       0.81      0.59      0.68      1296

        accuracy                           0.78      4086
       macro avg       0.78      0.80      0.78      4086
    weighted avg       0.80      0.78      0.78      4086



In [19]:
#Build training pipeline using  SVM Model


from sklearn import svm
from sklearn.svm import SVC

from sklearn.linear_model import SGDClassifier
text_clf3 = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer(use_idf=True)),
                      ('clf', svm.LinearSVC(C=1.0))
                    ])
text_clf3.fit(X_train, y_train) 
    
predicted3 = text_clf3.predict(X_test)
 


In [20]:
print(metrics.confusion_matrix(y_test, predicted3))


[[1067  120   10   26]
 [  57  544    9  116]
 [   5   11  732   93]
 [  50  239  242  765]]


In [21]:
print(np.mean(predicted3 == y_test) )


0.7606461086637298


In [22]:
print(metrics.classification_report(y_test, predicted3))

                  precision    recall  f1-score   support

Business Analyst       0.91      0.87      0.89      1223
    Data Analyst       0.60      0.75      0.66       726
   Data Engineer       0.74      0.87      0.80       841
  Data Scientist       0.77      0.59      0.67      1296

        accuracy                           0.76      4086
       macro avg       0.75      0.77      0.75      4086
    weighted avg       0.77      0.76      0.76      4086



In [20]:
test=pd.read_excel('V3.0 Project OA Data_excel_Testingdata.xlsx')
test.head(3)
test1=test['Clean Job Title']
test1=list(test1)
test1

['ARCHITECT DATA ANALYSIS OF RESEARCH DOMAIN',
 'ASSISTANT MANAGER DATA SCIENTIST',
 'LEAD DATA SCIENTIST']

In [21]:
#Prediction on new documents
for i in test1:
    docs_new = [i]
    predicted = text_clf2.predict(docs_new)
    print(predicted)

['Data Scientist']
['Data Scientist']
['Data Scientist']


In [12]:
#from sklearn.metrics import roc_curve
#from sklearn.metrics import roc_auc_score
#from matplotlib import pyplot

#a = np.array(tuple(y_test))
#a.ndim

#np.reshape(lr_probs,6)

In [14]:

# predict probabilities
#lr_probs = clf2.predict_proba(X_test)
# keep probabilities for the positive outcome only
#lr_probs = lr_probs[:, 1]
# calculate scores
#y_test.ndim
#lr_auc = roc_auc_score(y_test, lr_probs,multi_class="ovo")
# summarize scores


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
#roc = {label: [] for label in multi_class_series.unique()}
#for label in multi_class_series.unique():
    #selected_classifier.fit(train_set_dataframe, train_class == label)
    #predictions_proba = selected_classifier.predict_proba(test_set_dataframe)
    #roc[label] += roc_auc_score(test_class, predictions_proba[:,1])

#print(' ROC AUC=%.3f' % (lr_auc))
# calculate roc curves

#lr_fpr, lr_tpr, _ = roc_curve(testy, lr_probs)
# plot the roc curve for the model

#pyplot.plot(lr_fpr, lr_tpr, marker='.', label='Classification')
# axis labels
#pyplot.xlabel('False Positive Rate')
#pyplot.ylabel('True Positive Rate')
# show the legend
#pyplot.legend()
# show the plot
#pyplot.show()